-- Zap does not maintain a down migration: LSP and persistent workspace history
-- have been permanently retired, so there is no reasonable rollback target.
-- This empty file is kept to satisfy the diesel migration directory convention.
